"use client";
import { useEffect, useState } from "react";

export const defaultData = {
 en:{nav:["About","Skills","Experience","Project","Education","Contact"],kicker:"IT SUPPORT · SYSTEMS · INFRASTRUCTURE",title:"I keep technology reliable, secure, and ready for work.",intro:"IT Technical Support Specialist based in Riyadh, with 2+ years of hands-on experience supporting users, cloud services, networks, POS systems, and business-critical operations.",cta:"Contact me",cv:"Download CV",loc:"Riyadh, Saudi Arabia",aboutTitle:"Practical support. Measurable uptime.",about:"I solve the technical issues that slow teams down—from Microsoft 365 administration and endpoint troubleshooting to branch connectivity, POS platforms, and operational integrations. My focus is clear communication, fast diagnosis, and dependable results.",stats:[["2+","Years of experience"],["100+","Users supported"],["Tier 1/2","Technical support"]],skillsTitle:"Technical toolkit",skills:[["Cloud & identity","Microsoft 365, Entra ID, Exchange Online, RBAC, user lifecycle"],["Networks","TCP/IP, DNS, DHCP, VPN, VLAN basics, routers, switches, access points"],["Business systems","Odoo Helpdesk & CRM, Foodics POS, self-service kiosks, SQL basics"],["Security & support","Microsoft Defender, CrowdStrike, Windows 10/11, RDP, AnyDesk, RustDesk"]],expTitle:"Experience",role:"IT Technical Support Specialist",company:"International Dishes Company",period:"June 2024 — Present",bullets:["Provide Tier 1 and Tier 2 support for 100+ users across multi-branch operations.","Administer Microsoft 365 and Entra ID accounts, groups, licenses, and Exchange policies.","Deploy and maintain Foodics POS, kiosks, payment terminals, printers, and delivery integrations.","Troubleshoot LAN/Wi-Fi, routers, access points, static IPs, and VPN connections."],projectTitle:"Featured project",projectName:"Customer Service CRM in Odoo",project:"Designed and implemented a CRM workflow inside Odoo to help the customer service team organize requests, track follow-ups, clarify ownership, and improve visibility across the support process.",tags:["Odoo CRM","Workflow Design","Customer Service","Process Improvement"],eduTitle:"Education",degree:"Bachelor of Information Technology (BIT)",school:"Arab Open University — Riyadh",year:"Class of 2025",contactTitle:"Let’s make IT work better.",contactText:"Open to IT Support, Helpdesk, Desktop Support, Systems, and Infrastructure opportunities in Riyadh and the Eastern Province.",wa:"WhatsApp",mail:"Email",footer:"Built around reliable support and continuous improvement."},
 ar:{nav:["نبذة","المهارات","الخبرة","المشروع","التعليم","التواصل"],kicker:"الدعم التقني · الأنظمة · البنية التحتية",title:"أحافظ على التقنية مستقرة وآمنة وجاهزة للعمل.",intro:"أخصائي دعم فني في الرياض بخبرة عملية تتجاوز سنتين في دعم المستخدمين والخدمات السحابية والشبكات وأنظمة نقاط البيع والعمليات الحيوية للشركات.",cta:"تواصل معي",cv:"تحميل السيرة الذاتية",loc:"الرياض، السعودية",aboutTitle:"دعم عملي. واستمرارية يمكن الاعتماد عليها.",about:"أحل المشكلات التقنية التي تعطل فرق العمل، بداية من إدارة Microsoft 365 ودعم الأجهزة، وصولًا إلى ربط الفروع وأنظمة نقاط البيع والتكاملات التشغيلية. أركز على التواصل الواضح والتشخيص السريع والنتائج الموثوقة.",stats:[["+2","سنوات خبرة"],["+100","مستخدم تم دعمهم"],["Tier 1/2","دعم فني"]],skillsTitle:"المهارات التقنية",skills:[["السحابة والهوية","Microsoft 365 وEntra ID وExchange Online وإدارة الصلاحيات والمستخدمين"],["الشبكات","TCP/IP وDNS وDHCP وVPN وأساسيات VLAN والراوترات والسويتشات ونقاط الوصول"],["أنظمة الأعمال","Odoo Helpdesk وCRM وFoodics POS وأجهزة الخدمة الذاتية وأساسيات SQL"],["الأمن والدعم","Microsoft Defender وCrowdStrike وWindows 10/11 وRDP وAnyDesk وRustDesk"]],expTitle:"الخبرة العملية",role:"أخصائي دعم فني لتقنية المعلومات",company:"شركة الأطباق العالمية",period:"يونيو 2024 — حتى الآن",bullets:["تقديم دعم فني من المستوى الأول والثاني لأكثر من 100 مستخدم ضمن عمليات متعددة الفروع.","إدارة حسابات ومجموعات وتراخيص Microsoft 365 وEntra ID وسياسات Exchange.","تركيب وصيانة Foodics POS وأجهزة الخدمة الذاتية وأجهزة الدفع والطابعات وتكاملات التوصيل.","استكشاف مشاكل LAN وWi-Fi والراوترات ونقاط الوصول وعناوين IP الثابتة واتصالات VPN."],projectTitle:"مشروع مميز",projectName:"إنشاء نظام CRM لخدمة العملاء داخل Odoo",project:"تصميم وتنفيذ مسار عمل لنظام CRM داخل Odoo لمساعدة فريق خدمة العملاء على تنظيم الطلبات ومتابعة الحالات وتحديد المسؤوليات وتحسين وضوح مراحل الدعم.",tags:["Odoo CRM","تصميم سير العمل","خدمة العملاء","تحسين العمليات"],eduTitle:"التعليم",degree:"بكالوريوس تقنية المعلومات (BIT)",school:"الجامعة العربية المفتوحة — الرياض",year:"دفعة 2025",contactTitle:"معًا نجعل التقنية تعمل بشكل أفضل.",contactText:"متاح لفرص الدعم الفني وHelpdesk ودعم أجهزة المستخدمين والأنظمة والبنية التحتية في الرياض والمنطقة الشرقية.",wa:"واتساب",mail:"البريد الإلكتروني",footer:"دعم موثوق وتطوير مستمر."}
};
const ids=["about","skills","experience","project","education","contact"];
export default function Home(){const[lang,setLang]=useState<"en"|"ar">("en");const[content,setContent]=useState<any>(defaultData);const[links,setLinks]=useState({whatsapp:"966510565165",email:"mohammed.saber.dev@gmail.com",linkedin:"https://linkedin.com/in/mohammed-saber-it"});useEffect(()=>{fetch("/api/content").then(r=>r.json()).then(x=>{if(x?.content){setContent(x.content);if(x.links)setLinks(x.links)}}).catch(()=>{})},[]);const t=content[lang];const rtl=lang==="ar";return <main dir={rtl?"rtl":"ltr"} className={rtl?"rtl":""}>
 <header><a className="brand" href="#top"><i>MS</i> Mohammed Saber</a><nav>{t.nav.map((x,i)=><a key={x} href={`#${ids[i]}`}>{x}</a>)}</nav><button onClick={()=>setLang(rtl?"en":"ar")}>{rtl?"EN":"عربي"}</button></header>
 <section id="top" className="wrap hero"><div><p className="eyebrow">{t.kicker}</p><h1>{t.title}</h1><p className="lead">{t.intro}</p><div className="actions"><a className="primary" href="#contact">{t.cta}</a><a className="secondary" href="/api/media/cv" download>{t.cv} ↓</a></div><small>⌖ {t.loc}</small></div><div className="portrait"><span/><img src="/api/media/photo" alt="Mohammed Saber"/><b>● Available for opportunities</b></div></section>
 <section id="about" className="wrap split"><div><p className="label">01 / ABOUT</p><h2>{t.aboutTitle}</h2></div><div><p className="copy">{t.about}</p><div className="stats">{t.stats.map(([n,l])=><div key={l}><strong>{n}</strong><small>{l}</small></div>)}</div></div></section>
 <section id="skills" className="wrap"><p className="label">02 / SKILLS</p><h2>{t.skillsTitle}</h2><div className="skills">{t.skills.map(([n,d],i)=><article key={n}><b>0{i+1}</b><h3>{n}</h3><p>{d}</p></article>)}</div></section>
 <section id="experience" className="wrap"><p className="label">03 / EXPERIENCE</p><h2>{t.expTitle}</h2><article className="experience"><div><div><h3>{t.role}</h3><p>{t.company}</p></div><span>{t.period}</span></div><ul>{t.bullets.map(x=><li key={x}>{x}</li>)}</ul></article></section>
 <section id="project" className="dark"><div className="wrap split"><div><p className="label">04 / PROJECT</p><h2>{t.projectTitle}</h2></div><article className="project"><i>O</i><h3>{t.projectName}</h3><p>{t.project}</p><div>{t.tags.map(x=><span key={x}>{x}</span>)}</div></article></div></section>
 <section id="education" className="wrap"><p className="label">05 / EDUCATION</p><h2>{t.eduTitle}</h2><article className="education"><span>2025</span><div><h3>{t.degree}</h3><p>{t.school}</p></div><b>{t.year}</b></article></section>
 <section id="contact" className="dark contact"><div className="wrap"><p className="label">06 / CONTACT</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div><a href={`https://wa.me/${links.whatsapp.replace(/\D/g,"")}`} target="_blank">{t.wa} ↗</a><a href={`mailto:${links.email}`}>{t.mail} ↗</a><a href={links.linkedin} target="_blank">LinkedIn ↗</a></div></div></section>
 <footer><span>© 2026 Mohammed Saber</span><span>{t.footer}</span></footer>
 </main>}
